project_id = "ugsqhlnulfouubuedpxq"

[functions.check-answer]
verify_jwt = true

[functions.submit-game]
verify_jwt = true

[functions.get-server-time]
verify_jwt = false

[functions.submit-tournament-round]
verify_jwt = true
